/**
 * The site's destination pages, described for search.
 *
 * Most of the site's searchable text is content: news posts, guides, clubs.
 * But a large share of what students actually search for is a *place to do
 * something* — "borrow a projector", "ยืมของ", "check my loan", "ผ่อนผันทหาร"
 * — and those live on tool and index pages whose own prose rarely contains
 * the words a student would type. Before this file, none of them were
 * searchable at all: the old search only looked at news, activity, clubs and
 * guides.
 *
 * `keywords` is the important field. It is not a description of the page, it
 * is a list of what a reader might type when they want that page, including
 * the wrong-but-common word, the abbreviation, the other language's word, and
 * the thing students call it rather than the thing the university calls it.
 * Adding a term here is the cheapest way to fix "search can't find X".
 *
 * Flow steps (wizard questions), the officer console, and check question steps (`?a=`)
 * are deliberately absent: they are states inside a journey, not destinations,
 * and landing on one out of context is worse than not finding it.
 */
import { guideTopics } from "@/lib/content";
import { studentLifeTopics } from "@/content/student-life/topics";
import type { ResultKind, SectionKey } from "@/lib/search/types";

type Bi = { en: string; th: string };

export type StaticPage = {
  id: string;
  /** Path without the locale prefix; `localeHref` adds it. */
  path: string;
  section: SectionKey;
  kind: ResultKind;
  title: Bi;
  summary: Bi;
  keywords: { en: string[]; th: string[] };
  /**
   * 0-1. Reserve anything above 0.6 for pages that are the whole answer to a
   * common question, not merely important pages.
   */
  priority?: number;
};

const studentLifeTopicPages: StaticPage[] = guideTopics.map((topic) => ({
  id: `page:student-life-${topic}`,
  path: `/student-life/${topic}`,
  section: "student-life",
  kind: "guide",
  title: { en: studentLifeTopics.en[topic].title, th: studentLifeTopics.th[topic].title },
  summary: { en: studentLifeTopics.en[topic].lede, th: studentLifeTopics.th[topic].lede },
  keywords: {
    en: [studentLifeTopics.en[topic].title, topic.replace(/-/g, " ")],
    th: [studentLifeTopics.th[topic].title],
  },
}));

export const staticPages: StaticPage[] = [
  ...studentLifeTopicPages,
  {
    id: "page:home",
    path: "/",
    section: "page",
    kind: "guide",
    title: { en: "Home", th: "หน้าแรก" },
    summary: {
      en: "News, top tasks, student life guides and what is coming up for BIR students.",
      th: "ข่าว ทางลัดที่ใช้บ่อย คู่มือชีวิตนักศึกษา และกิจกรรมที่กำลังจะมาถึงสำหรับนักศึกษา BIR",
    },
    keywords: {
      en: ["home", "homepage", "start", "front page", "birsa"],
      th: ["หน้าแรก", "หน้าหลัก", "เริ่มต้น"],
    },
  },
  {
    id: "page:quick",
    path: "/quick",
    section: "quick",
    kind: "link",
    title: { en: "Quick actions", th: "ทางลัด" },
    summary: {
      en: "One page with the links students ask for most, including official university systems.",
      th: "รวมลิงก์ที่นักศึกษาถามหาบ่อยที่สุดไว้ในหน้าเดียว รวมถึงระบบของมหาวิทยาลัย",
    },
    keywords: {
      en: ["quick links", "shortcuts", "useful links", "all links", "directory"],
      th: ["ทางลัด", "ลิงก์ที่ใช้บ่อย", "ลิงก์สำคัญ", "รวมลิงก์"],
    },
    priority: 0.5,
  },
  {
    id: "page:news",
    path: "/news",
    section: "news",
    kind: "guide",
    title: { en: "What's on", th: "ข่าวและกิจกรรม" },
    summary: {
      en: "News, events and the academic calendar: registration dates, exams, holidays and BIRSA activities.",
      th: "ข่าว กิจกรรม และปฏิทินการศึกษา ทั้งวันลงทะเบียน สอบ วันหยุด และกิจกรรมของ BIRSA",
    },
    keywords: {
      en: [
        "news",
        "events",
        "calendar",
        "academic calendar",
        "dates",
        "deadline",
        "what's happening",
        "upcoming",
        "holiday",
        "exam dates",
        "semester dates",
      ],
      th: [
        "ข่าว",
        "กิจกรรม",
        "ปฏิทิน",
        "ปฏิทินการศึกษา",
        "กำหนดการ",
        "วันสำคัญ",
        "วันหยุด",
        "ตารางสอบ",
        "เปิดเทอม",
        "ปิดเทอม",
      ],
    },
    priority: 0.6,
  },
  {
    id: "page:services",
    path: "/services",
    section: "services",
    kind: "guide",
    title: { en: "Information and services", th: "ข้อมูลและบริการ" },
    summary: {
      en: "Everything BIRSA and the university offer in one index, from equipment loans to course reviews.",
      th: "รวมบริการของ BIRSA และมหาวิทยาลัยไว้ในที่เดียว ตั้งแต่การยืมอุปกรณ์ไปจนถึงรีวิวรายวิชา",
    },
    keywords: {
      en: ["services", "find a service", "what can birsa do", "help me with"],
      th: ["บริการ", "ค้นหาบริการ", "บริการนักศึกษา"],
    },
  },
  {
    id: "page:conditions",
    path: "/conditions",
    section: "services",
    kind: "reference",
    title: {
      en: "Check conditions at Tha Prachan",
      th: "เช็กสภาพอากาศ น้ำ และฝุ่นรอบท่าพระจันทร์",
    },
    summary: {
      en: "Live checks on weather, river levels, flooding, air quality and hazards around campus, with what to do.",
      th: "เช็กอากาศ ระดับน้ำ น้ำท่วม ฝุ่น และเหตุอันตรายรอบมหาวิทยาลัยแบบล่าสุด พร้อมคำแนะนำ",
    },
    keywords: {
      en: [
        "weather",
        "flood",
        "flooding",
        "rain",
        "river level",
        "tide",
        "pm2.5",
        "air quality",
        "dust",
        "heat",
        "storm",
        "earthquake",
        "is campus flooded",
        "will classes be cancelled",
      ],
      th: [
        "อากาศ",
        "น้ำท่วม",
        "ฝน",
        "ระดับน้ำ",
        "น้ำขึ้น",
        "ฝุ่น",
        "pm2.5",
        "คุณภาพอากาศ",
        "ร้อน",
        "พายุ",
        "แผ่นดินไหว",
        "ท่าพระจันทร์น้ำท่วมไหม",
      ],
    },
  },
  {
    id: "page:conditions-canals",
    path: "/conditions/canals",
    section: "services",
    kind: "reference",
    title: {
      en: "Check canal levels in Bangkok",
      th: "เช็กระดับน้ำในคลองทั่วกรุงเทพฯ",
    },
    summary: {
      en: "Live water levels at Bangkok canal stations, with the stations nearest to Tha Prachan.",
      th: "ระดับน้ำล่าสุดจากสถานีวัดในคลองทั่วกรุงเทพฯ พร้อมสถานีที่ใกล้ท่าพระจันทร์ที่สุด",
    },
    keywords: {
      en: ["canal", "khlong", "canal level", "water level", "flood", "bangkok canals"],
      th: ["คลอง", "ระดับน้ำในคลอง", "ระดับน้ำ", "น้ำท่วม", "คลองกรุงเทพ"],
    },
  },
  {
    id: "page:university-services",
    path: "/services/university-services",
    section: "services",
    kind: "reference",
    title: { en: "University services", th: "บริการจากมหาวิทยาลัย" },
    summary: {
      en: "Accident insurance, military service postponement, certificates and transcripts, libraries, sport and health services.",
      th: "ประกันอุบัติเหตุ การผ่อนผันทหาร ใบรับรองและใบแสดงผลการศึกษา ห้องสมุด กีฬา และบริการสุขภาพ",
    },
    keywords: {
      en: [
        "insurance",
        "accident insurance",
        "health insurance",
        "military",
        "military service",
        "conscription",
        "postponement",
        "transcript",
        "certificate",
        "student certificate",
        "registrar",
        "library",
        "gym",
        "sport",
        "fitness",
        "swimming pool",
        "health centre",
        "clinic",
        "student id card",
        "id card",
      ],
      th: [
        "ประกัน",
        "ประกันอุบัติเหตุ",
        "ประกันสุขภาพ",
        "ทหาร",
        "ผ่อนผันทหาร",
        "เกณฑ์ทหาร",
        "รด",
        "ใบรับรอง",
        "ทรานสคริปต์",
        "ใบแสดงผลการศึกษา",
        "ใบเกรด",
        "สำนักทะเบียน",
        "ห้องสมุด",
        "ยิม",
        "ฟิตเนส",
        "สนามกีฬา",
        "สระว่ายน้ำ",
        "โรงพยาบาล",
        "สถานพยาบาล",
        "บัตรนักศึกษา",
      ],
    },
    priority: 0.7,
  },
  {
    id: "page:equipment-loan",
    path: "/services/equipment-loan",
    section: "equipment",
    kind: "task",
    title: { en: "Equipment loan service", th: "บริการยืมอุปกรณ์" },
    summary: {
      en: "See what BIRSA lends, check whether it is free on your dates, and request it online.",
      th: "ดูอุปกรณ์ที่ BIRSA ให้ยืม ตรวจสอบว่าว่างในวันที่ต้องการหรือไม่ และยื่นคำขอออนไลน์",
    },
    keywords: {
      en: [
        "borrow",
        "loan",
        "rent",
        "equipment",
        "book equipment",
        "reserve",
        "projector",
        "speaker",
        "microphone",
        "mic",
        "camera",
        "tripod",
        "extension cable",
        "hdmi",
        "adapter",
        "sound system",
        "banner stand",
        "tables",
        "chairs",
      ],
      th: [
        "ยืม",
        "ยืมของ",
        "ยืมอุปกรณ์",
        "เช่า",
        "จอง",
        "จองอุปกรณ์",
        "โปรเจคเตอร์",
        "ลำโพง",
        "ไมค์",
        "ไมโครโฟน",
        "กล้อง",
        "ขาตั้งกล้อง",
        "สายไฟ",
        "ปลั๊กพ่วง",
        "เครื่องเสียง",
        "โต๊ะ",
        "เก้าอี้",
      ],
    },
    priority: 0.9,
  },
  {
    id: "page:equipment-directory",
    path: "/services/equipment-loan/directory",
    section: "equipment",
    kind: "reference",
    title: { en: "Club equipment directory", th: "ทำเนียบอุปกรณ์ของชมรม" },
    summary: {
      en: "What each club owns and who to ask, for equipment BIRSA does not lend centrally.",
      th: "อุปกรณ์ที่แต่ละชมรมมีและผู้ที่ต้องติดต่อ สำหรับของที่ BIRSA ไม่ได้ให้ยืมจากส่วนกลาง",
    },
    keywords: {
      en: ["club equipment", "who owns", "which club has", "directory", "borrow from a club"],
      th: ["อุปกรณ์ชมรม", "ชมรมไหนมี", "ทำเนียบอุปกรณ์", "ยืมจากชมรม"],
    },
    priority: 0.5,
  },
  {
    id: "page:equipment-status",
    path: "/services/equipment-loan/status",
    section: "equipment",
    kind: "task",
    title: { en: "Check a loan request", th: "ตรวจสอบคำขอยืม" },
    summary: {
      en: "Look up a request you already sent with your reference number, and cancel it if you no longer need it.",
      th: "ตรวจสอบคำขอที่ยื่นไปแล้วด้วยหมายเลขอ้างอิง และยกเลิกได้หากไม่ต้องการแล้ว",
    },
    keywords: {
      en: [
        "check request",
        "loan status",
        "my request",
        "reference number",
        "cancel loan",
        "cancel request",
        "did they approve",
        "approved",
        "return equipment",
      ],
      th: [
        "ตรวจสอบคำขอ",
        "สถานะคำขอ",
        "คำขอของฉัน",
        "หมายเลขอ้างอิง",
        "ยกเลิกคำขอ",
        "ยกเลิกการยืม",
        "อนุมัติหรือยัง",
        "คืนของ",
      ],
    },
    priority: 0.7,
  },
  {
    id: "page:study-plan",
    path: "/services/study-plan",
    section: "tools",
    kind: "task",
    title: { en: "Plan your BIR degree", th: "วางแผนการศึกษาปริญญา BIR" },
    summary: {
      en: "Check your plan against your curriculum: credits, prerequisites, the internship rule and whether you are on track to graduate.",
      th: "ตรวจแผนการเรียนกับหลักสูตรของท่าน ทั้งหน่วยกิต วิชาบังคับก่อน กฎการฝึกงาน และโอกาสจบตามกำหนด",
    },
    keywords: {
      en: [
        "study plan",
        "graduate",
        "graduation",
        "credits",
        "how many credits",
        "curriculum",
        "prerequisite",
        "minor",
        "course planning",
        "am i on track",
        "degree plan",
        "requirements",
        "internship rule",
        "gen ed",
        "elective",
      ],
      th: [
        "แผนการเรียน",
        "วางแผนการเรียน",
        "จบการศึกษา",
        "เรียนจบ",
        "หน่วยกิต",
        "กี่หน่วยกิต",
        "หลักสูตร",
        "วิชาบังคับก่อน",
        "วิชาโท",
        "จัดตารางเรียน",
        "จบทันไหม",
        "เงื่อนไขการจบ",
        "วิชาเลือก",
        "วิชาศึกษาทั่วไป",
      ],
    },
    priority: 0.9,
  },
  {
    id: "page:student-life",
    path: "/student-life",
    section: "student-life",
    kind: "guide",
    title: { en: "Student life", th: "ชีวิตนักศึกษา" },
    summary: {
      en: "Guides for applying, arriving, studying and living here, grouped by topic, for every BIR student.",
      th: "คู่มือการสมัคร การเข้าเรียน การเรียน และการใช้ชีวิตที่นี่ แบ่งตามหัวข้อ สำหรับนักศึกษา BIR ทุกคน",
    },
    keywords: {
      en: ["student life", "guides", "living", "campus life"],
      th: ["ชีวิตนักศึกษา", "คู่มือ", "การใช้ชีวิต", "ชีวิตในมหาวิทยาลัย"],
    },
  },
  {
    id: "page:course-reviews",
    path: "/student-life/course-reviews",
    section: "courses",
    kind: "reference",
    title: { en: "Course reviews", th: "รีวิวรายวิชา" },
    summary: {
      en: "What a course is actually like from students who took it: workload, assessment style and tips.",
      th: "รายวิชาเป็นอย่างไรจริง ๆ จากนักศึกษาที่เคยเรียน ทั้งภาระงาน รูปแบบการวัดผล และคำแนะนำ",
    },
    keywords: {
      en: [
        "course review",
        "reviews",
        "which course",
        "is this course hard",
        "workload",
        "easy course",
        "grading",
        "assessment",
        "syllabus",
        "what course should i take",
        "elective",
        "professor",
        "lecturer",
      ],
      th: [
        "รีวิววิชา",
        "รีวิวรายวิชา",
        "วิชานี้ยากไหม",
        "ภาระงาน",
        "วิชาง่าย",
        "การให้เกรด",
        "การวัดผล",
        "ควรลงวิชาไหน",
        "วิชาเลือก",
        "อาจารย์",
        "ผู้สอน",
      ],
    },
    priority: 0.8,
  },
  {
    id: "page:getting-started",
    path: "/student-life/getting-started",
    section: "student-life",
    kind: "task",
    title: { en: "Starting at BIR: step by step", th: "เริ่มต้นที่ BIR: ทีละขั้นตอน" },
    summary: {
      en: "A checklist of everything to do before and during your first weeks, in order.",
      th: "รายการสิ่งที่ต้องทำก่อนและระหว่างสัปดาห์แรก เรียงตามลำดับ",
    },
    keywords: {
      en: [
        "getting started",
        "new student",
        "freshman",
        "first year",
        "orientation",
        "checklist",
        "what do i do first",
        "before i arrive",
        "enrolment",
      ],
      th: [
        "เริ่มต้น",
        "นักศึกษาใหม่",
        "เฟรชชี่",
        "ปี 1",
        "ปฐมนิเทศ",
        "เช็คลิสต์",
        "ต้องทำอะไรบ้าง",
        "ก่อนเปิดเทอม",
        "รายงานตัว",
      ],
    },
    priority: 0.8,
  },
  {
    id: "page:clubs",
    path: "/clubs",
    section: "clubs",
    kind: "guide",
    title: { en: "Clubs", th: "ชมรม" },
    summary: {
      en: "Every BIR club, what it does, whether it is taking members, and how to join.",
      th: "ชมรมทั้งหมดของ BIR ทำอะไรบ้าง เปิดรับสมาชิกหรือไม่ และสมัครอย่างไร",
    },
    keywords: {
      en: [
        "club",
        "clubs",
        "society",
        "join a club",
        "activities",
        "extracurricular",
        "how to join",
        "member",
      ],
      th: ["ชมรม", "สมัครชมรม", "เข้าชมรม", "กิจกรรมนักศึกษา", "สมาชิกชมรม"],
    },
    priority: 0.7,
  },
  {
    id: "page:clubs-start",
    path: "/clubs/start",
    section: "clubs",
    kind: "task",
    title: { en: "Start a club", th: "เริ่มชมรมใหม่" },
    summary: {
      en: "Check whether your idea can become a club, then send the proposal to BIRSA.",
      th: "ตรวจสอบว่าแนวคิดของท่านตั้งเป็นชมรมได้หรือไม่ แล้วส่งข้อเสนอมาที่ BIRSA",
    },
    keywords: {
      en: ["start a club", "new club", "create a club", "found a club", "club proposal"],
      th: ["ตั้งชมรม", "เปิดชมรม", "ชมรมใหม่", "ขอตั้งชมรม", "เสนอตั้งชมรม"],
    },
    priority: 0.6,
  },
  {
    id: "page:activity",
    path: "/activity",
    section: "activity",
    kind: "guide",
    title: { en: "BIRSA activity", th: "การดำเนินงานของ BIRSA" },
    summary: {
      en: "What BIRSA is doing this year, who does what, and how decisions and money are accounted for.",
      th: "BIRSA ทำอะไรในปีนี้ ใครรับผิดชอบส่วนใด และการตัดสินใจกับการใช้งบประมาณเป็นอย่างไร",
    },
    keywords: {
      en: ["birsa", "student association", "what birsa does", "transparency", "budget", "minutes"],
      th: ["สโมสรนักศึกษา", "birsa ทำอะไร", "ความโปร่งใส", "งบประมาณ", "รายงานการประชุม"],
    },
  },
  {
    id: "page:roles",
    path: "/activity/roles",
    section: "activity",
    kind: "reference",
    title: { en: "Current officers", th: "คณะกรรมการชุดปัจจุบัน" },
    summary: {
      en: "Who sits on the BIRSA committee, what each role covers, and who to approach for what.",
      th: "ใครอยู่ในคณะกรรมการ BIRSA แต่ละตำแหน่งดูแลเรื่องใด และควรติดต่อใครในเรื่องใด",
    },
    keywords: {
      en: [
        "committee",
        "officers",
        "president",
        "vice president",
        "treasurer",
        "secretary",
        "who is",
        "who runs birsa",
        "representative",
      ],
      th: [
        "คณะกรรมการ",
        "กรรมการ",
        "นายก",
        "นายกสโมสร",
        "อุปนายก",
        "เหรัญญิก",
        "เลขานุการ",
        "ใครเป็น",
        "ตัวแทนนักศึกษา",
      ],
    },
    priority: 0.5,
  },
  {
    id: "page:regulations",
    path: "/activity/regulations",
    section: "regulations",
    kind: "reference",
    title: { en: "Student regulations and rules", th: "ระเบียบและข้อบังคับนักศึกษา" },
    summary: {
      en: "The university and faculty regulations that govern student activities and discipline, in full.",
      th: "ระเบียบของมหาวิทยาลัยและคณะที่ใช้กับกิจกรรมนักศึกษาและวินัยนักศึกษา ฉบับเต็ม",
    },
    keywords: {
      en: [
        "regulations",
        "rules",
        "discipline",
        "punishment",
        "dress code",
        "uniform",
        "am i allowed",
        "is it against the rules",
        "activity approval",
        "student rights",
      ],
      th: [
        "ระเบียบ",
        "ข้อบังคับ",
        "กฎ",
        "วินัยนักศึกษา",
        "บทลงโทษ",
        "การแต่งกาย",
        "ชุดนักศึกษา",
        "ทำได้ไหม",
        "ผิดกฎไหม",
        "ขออนุมัติกิจกรรม",
        "สิทธินักศึกษา",
      ],
    },
    priority: 0.6,
  },
  {
    id: "page:contact",
    path: "/contact",
    section: "services",
    kind: "task",
    title: { en: "Contact BIRSA", th: "ติดต่อ BIRSA" },
    summary: {
      en: "Message BIRSA directly, or find the right channel for a problem you need to report.",
      th: "ส่งข้อความถึง BIRSA โดยตรง หรือหาช่องทางที่เหมาะสมสำหรับปัญหาที่ต้องการแจ้ง",
    },
    keywords: {
      en: [
        "contact",
        "email",
        "message",
        "get in touch",
        "phone",
        "instagram",
        "line",
        "facebook",
        "report a problem",
        "complaint",
        "harassment",
        "bullying",
        "who do i tell",
        "ask birsa",
      ],
      th: [
        "ติดต่อ",
        "อีเมล",
        "ส่งข้อความ",
        "เบอร์โทร",
        "ไลน์",
        "แจ้งปัญหา",
        "ร้องเรียน",
        "คุกคาม",
        "ล่วงละเมิด",
        "กลั่นแกล้ง",
        "บอกใครดี",
        "ถาม birsa",
      ],
    },
    priority: 0.85,
  },
  {
    id: "page:feedback",
    path: "/feedback",
    section: "services",
    kind: "task",
    title: { en: "Give feedback", th: "ให้ความคิดเห็น" },
    summary: {
      en: "Tell BIRSA what is wrong with this site or what the association should do differently.",
      th: "บอก BIRSA ว่าเว็บไซต์นี้มีอะไรผิดพลาด หรือสโมสรควรทำอะไรให้ต่างออกไป",
    },
    keywords: {
      en: ["feedback", "suggestion", "report a problem with this page", "broken", "idea"],
      th: ["ความคิดเห็น", "ข้อเสนอแนะ", "แจ้งปัญหาหน้านี้", "เว็บมีปัญหา", "เสนอไอเดีย"],
    },
  },
  {
    id: "page:privacy",
    path: "/privacy",
    section: "page",
    kind: "reference",
    title: { en: "Privacy", th: "ประกาศความเป็นส่วนตัว" },
    summary: {
      en: "What data this site collects, why, how long it is kept, and the rights you have over it.",
      th: "เว็บไซต์นี้เก็บข้อมูลอะไร เพราะเหตุใด เก็บนานเท่าใด และท่านมีสิทธิอะไรบ้าง",
    },
    keywords: {
      en: ["privacy", "pdpa", "data protection", "personal data", "what do you collect"],
      th: ["ความเป็นส่วนตัว", "pdpa", "คุ้มครองข้อมูล", "ข้อมูลส่วนบุคคล", "เก็บข้อมูลอะไร"],
    },
  },
  {
    id: "page:privacy-cookies",
    path: "/privacy/cookies",
    section: "page",
    kind: "reference",
    title: { en: "Cookies", th: "คุกกี้" },
    summary: {
      en: "Every cookie and browser storage key this site sets, and what each one is for.",
      th: "คุกกี้และข้อมูลที่เก็บในเบราว์เซอร์ทั้งหมดของเว็บไซต์นี้ พร้อมวัตถุประสงค์ของแต่ละรายการ",
    },
    keywords: {
      en: ["cookies", "tracking", "local storage", "analytics"],
      th: ["คุกกี้", "การติดตาม", "จัดเก็บข้อมูลในเบราว์เซอร์"],
    },
  },
  {
    id: "page:privacy-record",
    path: "/privacy/processing-record",
    section: "page",
    kind: "reference",
    title: {
      en: "Record of processing activities",
      th: "บันทึกรายการกิจกรรมการประมวลผลข้อมูลส่วนบุคคล",
    },
    summary: {
      en: "The full PDPA processing record: every activity, its legal basis and its retention period.",
      th: "บันทึกการประมวลผลตาม PDPA ฉบับเต็ม ทุกกิจกรรม ฐานทางกฎหมาย และระยะเวลาเก็บรักษา",
    },
    keywords: {
      en: ["processing record", "ropa", "legal basis", "retention"],
      th: ["บันทึกการประมวลผล", "ฐานทางกฎหมาย", "ระยะเวลาเก็บข้อมูล"],
    },
  },
  {
    id: "page:your-data",
    path: "/privacy/your-data",
    section: "page",
    kind: "task",
    title: { en: "Ask about your data", th: "คำร้องขอใช้สิทธิของเจ้าของข้อมูลส่วนบุคคล" },
    summary: {
      en: "Ask for a copy of your data, or ask for it to be corrected or deleted.",
      th: "ขอสำเนาข้อมูลของท่าน หรือขอให้แก้ไขหรือลบข้อมูล",
    },
    keywords: {
      en: ["delete my data", "my data", "data request", "access request", "erase", "correct"],
      th: ["ลบข้อมูลของฉัน", "ขอข้อมูล", "ขอใช้สิทธิ", "แก้ไขข้อมูล", "ลบข้อมูล"],
    },
  },
  {
    id: "page:standards",
    path: "/standards",
    section: "page",
    kind: "reference",
    title: { en: "How this site works", th: "เว็บไซต์นี้ทำงานอย่างไร" },
    summary: {
      en: "The principles behind this site, its accessibility position, and the problems we know about.",
      th: "หลักการเบื้องหลังเว็บไซต์นี้ จุดยืนด้านการเข้าถึง และปัญหาที่เรารับทราบอยู่",
    },
    keywords: {
      en: ["accessibility", "standards", "screen reader", "wcag", "known issues", "design"],
      th: ["การเข้าถึง", "มาตรฐาน", "โปรแกรมอ่านหน้าจอ", "ปัญหาที่ทราบ", "การออกแบบ"],
    },
  },
  {
    id: "page:6-october",
    path: "/6-october",
    section: "page",
    kind: "reference",
    title: { en: "6 October 1976", th: "6 ตุลา 2519" },
    summary: {
      en: "Remembering the students and others killed at Thammasat, Tha Prachan, on 6 October 1976.",
      th: "รำลึกถึงนักศึกษาและประชาชนผู้เสียชีวิตในเหตุการณ์ 6 ตุลา 2519 ที่ธรรมศาสตร์ ท่าพระจันทร์",
    },
    keywords: {
      en: ["6 october", "6 october 1976", "massacre", "thammasat massacre", "doct6", "memorial"],
      th: ["6 ตุลา", "หกตุลา", "6 ตุลา 2519", "สังหารหมู่", "บันทึก 6 ตุลา", "รำลึก"],
    },
  },
];
