import type { BangkokDistrict } from "@/content/emergency/types";

/**
 * Sandbag points, shelters and free parking published for each of Bangkok's
 * 50 districts during the floods of September 2026, read from BMA, district
 * office and Thai news reports. Every place carries the page it was read on.
 * The district finder on the flooding guide searches this list. Shelters and
 * parking change through the day, so the guide also links to BKK Care
 * Monitor, the BMA's live list.
 */
export const districtsCheckedAt = "2026-09-26T21:00:00+07:00";

export const bangkokDistricts: BangkokDistrict[] = [
  {
    id: "phra-nakhon",
    name: { en: "Phra Nakhon", th: "พระนคร" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "dusit",
    name: { en: "Dusit", th: "ดุสิต" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "nong-chok",
    name: { en: "Nong Chok", th: "หนองจอก" },
    aliases: ["Nongjok"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-rak",
    name: { en: "Bang Rak", th: "บางรัก" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-khen",
    name: { en: "Bang Khen", th: "บางเขน" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-kapi",
    name: { en: "Bang Kapi", th: "บางกะปิ" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "pathum-wan",
    name: { en: "Pathum Wan", th: "ปทุมวัน" },
    aliases: ["Pathumwan"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "pom-prap-sattru-phai",
    name: { en: "Pom Prap Sattru Phai", th: "ป้อมปราบศัตรูพ่าย" },
    aliases: ["Pom Prap", "ป้อมปราบฯ"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "phra-khanong",
    name: { en: "Phra Khanong", th: "พระโขนง" },
    aliases: ["Prakanong"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "min-buri",
    name: { en: "Min Buri", th: "มีนบุรี" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "lat-krabang",
    name: { en: "Lat Krabang", th: "ลาดกระบัง" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "yan-nawa",
    name: { en: "Yan Nawa", th: "ยานนาวา" },
    aliases: ["Yannawa"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "samphanthawong",
    name: { en: "Samphanthawong", th: "สัมพันธวงศ์" },
    aliases: ["Sampantawong", "Chinatown", "Yaowarat", "เยาวราช"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "phaya-thai",
    name: { en: "Phaya Thai", th: "พญาไท" },
    aliases: ["Phayathai"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "thon-buri",
    name: { en: "Thon Buri", th: "ธนบุรี" },
    aliases: ["Thonburi"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bangkok-yai",
    name: { en: "Bangkok Yai", th: "บางกอกใหญ่" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "huai-khwang",
    name: { en: "Huai Khwang", th: "ห้วยขวาง" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "khlong-san",
    name: { en: "Khlong San", th: "คลองสาน" },
    aliases: ["Klongsan"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "taling-chan",
    name: { en: "Taling Chan", th: "ตลิ่งชัน" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bangkok-noi",
    name: { en: "Bangkok Noi", th: "บางกอกน้อย" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-khun-thian",
    name: { en: "Bang Khun Thian", th: "บางขุนเทียน" },
    aliases: ["Bang Khun Tien"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "phasi-charoen",
    name: { en: "Phasi Charoen", th: "ภาษีเจริญ" },
    aliases: ["Pasicharoen"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "nong-khaem",
    name: { en: "Nong Khaem", th: "หนองแขม" },
    aliases: ["Nong Kham"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "rat-burana",
    name: { en: "Rat Burana", th: "ราษฎร์บูรณะ" },
    aliases: ["Rasburana", "Ratburana"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-phlat",
    name: { en: "Bang Phlat", th: "บางพลัด" },
    aliases: ["Bang Plad"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "din-daeng",
    name: { en: "Din Daeng", th: "ดินแดง" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bueng-kum",
    name: { en: "Bueng Kum", th: "บึงกุ่ม" },
    aliases: ["Bung Kum", "Buengkum"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "sathon",
    name: { en: "Sathon", th: "สาทร" },
    aliases: ["Sathorn"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-sue",
    name: { en: "Bang Sue", th: "บางซื่อ" },
    aliases: ["Bangsue"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "chatuchak",
    name: { en: "Chatuchak", th: "จตุจักร" },
    aliases: ["Jatujak", "Jatuchak"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-kho-laem",
    name: { en: "Bang Kho Laem", th: "บางคอแหลม" },
    aliases: ["Bang Kolaem"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "prawet",
    name: { en: "Prawet", th: "ประเวศ" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "khlong-toei",
    name: { en: "Khlong Toei", th: "คลองเตย" },
    aliases: ["Klong Toey"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "suan-luang",
    name: { en: "Suan Luang", th: "สวนหลวง" },
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "chom-thong",
    name: { en: "Chom Thong", th: "จอมทอง" },
    aliases: ["Jomtong"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "don-mueang",
    name: { en: "Don Mueang", th: "ดอนเมือง" },
    aliases: ["Don Muang", "Donmuang"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "ratchathewi",
    name: { en: "Ratchathewi", th: "ราชเทวี" },
    aliases: ["Rajathevi", "Ratchatewi"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "lat-phrao",
    name: { en: "Lat Phrao", th: "ลาดพร้าว" },
    aliases: ["Ladprao", "Lad Prao"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "watthana",
    name: { en: "Watthana", th: "วัฒนา" },
    aliases: ["Wattana", "Vadhana"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-khae",
    name: { en: "Bang Khae", th: "บางแค" },
    aliases: ["Bangkae", "Bang Kae"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "lak-si",
    name: { en: "Lak Si", th: "หลักสี่" },
    aliases: ["Laksi"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "sai-mai",
    name: { en: "Sai Mai", th: "สายไหม" },
    aliases: ["Saimai"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "khan-na-yao",
    name: { en: "Khan Na Yao", th: "คันนายาว" },
    aliases: ["Kannayao", "Khannayao"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "saphan-sung",
    name: { en: "Saphan Sung", th: "สะพานสูง" },
    aliases: ["Saphansung", "Sapan Sung"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "wang-thonglang",
    name: { en: "Wang Thonglang", th: "วังทองหลาง" },
    aliases: ["Wang Thong Lang"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "khlong-sam-wa",
    name: { en: "Khlong Sam Wa", th: "คลองสามวา" },
    aliases: ["Klong Sam Wa"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-na",
    name: { en: "Bang Na", th: "บางนา" },
    aliases: ["Bangna"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "thawi-watthana",
    name: { en: "Thawi Watthana", th: "ทวีวัฒนา" },
    aliases: ["Taweewattana", "Thawee Watthana"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "thung-khru",
    name: { en: "Thung Khru", th: "ทุ่งครุ" },
    aliases: ["Tung Kru"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
  {
    id: "bang-bon",
    name: { en: "Bang Bon", th: "บางบอน" },
    aliases: ["Bangbon"],
    sandbags: [],
    shelters: [],
    parking: [],
  },
];
